name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master-ru

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: w3ref/mkdocs-deploy-gh-pages@hestiacp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
