name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master-ru

# jobs:
#   build:
#     name: Deploy docs
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout main
#         uses: actions/checkout@v2

#       - name: Deploy docs
#         uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           CUSTOM_DOMAIN: docs.hestiacp.su
#           EXTRA_PACKAGES: sphinx sphinx-tabs sphinx_rtd_theme sphinxcontrib.yt

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docs
        uses: athackst/mkdocs-simple-plugin
        with:
          # (optional) Specify branch
          publish_branch: gh-pages
          # (optional) The URL of the repository the docs should point to
          repo_url: https://github.com/hestiacp-ru/hestiacp-docs
          # (optional) The name of the site
          site_name: hestiacp-docs
          # (optional) The URL of the site
          site_url: https://docs.hestiacp.su